baseURL = "pathos-game.com"
languageCode = "en-us"
title = "Pathos"
paginate = 3

theme = "jeffprod"

publishDir = "docs"

[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"
